/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "design/processor_top.v:1" *)
module processor_top(clk, reset);
  (* src = "design/processor_top.v:1" *)
  input clk;
  (* src = "design/processor_top.v:1" *)
  input reset;
endmodule
